variables:
  PACKAGE_NAME: caen_frontend

stages:
  - build
  - upload
  - release

build:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/node:22.11
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      npm install
      export REACT_APP_CAEN=production
      npm run build
      ls -lh
    - echo "VERSION=$CI_COMMIT_TAG" > build.env
  artifacts:
    name: "frontend_build"
    paths:
      - build/
    reports:
      dotenv: build.env
    expire_in: 1 day

upload:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alpine/curl:8.9.1
  stage: upload
  needs: ['build']
  script:
    - ls -lh
    - tar -cvzf build.tar.gz build/
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${VERSION}/build.tar.gz"'


release_job:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  needs: ['upload']
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - ls -l
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Auto release with Gitlab CI'
    assets:
        links:
          - name: "build.tar.gz"
            url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${VERSION}/build.tar.gz"

