stages:
  - build
  - release

build:
  image: node:22.11
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      npm install
      export REACT_APP_CAEN=production
      npm run build
      tar -cvzf build.tar.gz build/
      ls -l
  artifacts:
    name: "frontend_build"
    paths:
      - build.tar.gz
    expire_in: 1 day

release_job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - ls -l
    - echo $CI_JOB_URL
  artifacts:
    name: "frontend_build"
    paths:
      - build.tar.gz
    expire_in: never
  release:
    tag_name: $CI_COMMIT_TAG
    name: 'Release $CI_COMMIT_TAG'
    description: 'Auto release with Gitlab CI'
    assets:
        links:
          - name: "frontend_build.tar.gz"
            url: "$CI_JOB_URL/artifacts/raw/build.tar.gz"

