name: release_action
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
      - name: Build frontend
        shell: bash
        run: |
          npm install
          export REACT_APP_CAEN=production
          npm run build
          ls -l
      - name: Prepare zip archive for release
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
          retention-days: 1



