name: release_action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Build frontend and zip it
        shell: bash
        run: |
          npm install
          npm run build
          zip -r build.zip ./build
          ls -l
      - name: Prepare release
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build.zip
          retention-days: 1



